spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=b00tc4mp
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update  # Or validate for production
spring.jpa.show-sql=true  # Optional